---
title: "reversie_analysis"
author: "Yeyun Xu"
date: "5/26/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#read data
data <- read.csv(file = 'combine.csv',na.strings = c("","NA"))
```

```{r}
#data cleaning (omit 90% of the missing data)
data<-data[, which(colMeans(!is.na(data)) > 0.8)]

data <-data[data$Property.Type == "RESI" &
                      data$Property.Sub.Type =="SFR",]


#get first letter in for subdivision column
subdivision_first_letter <- substr(data$Subdivision.Name,1,6)
#sign into a new columns
data$subdivision_first_letter <- subdivision_first_letter

```

```{r}
data <- data[!is.na(data$Year.Built),]
data[data$Year.Built <= 1990, "Building_Year"]<- "1990-"
data[data$Year.Built > 1990 & data$Year.Built <= 2011, "Building_Year"] <- "1990-2011"
data[data$Year.Built > 2011 & data$Year.Built <= 2021, "Building_Year"] <- "2011-2021"
data[data$Year.Built == 2022 , "Building_Year"] <- "2022"
```
#input
```{r}
# year <- readline(prompt="Enter years: ")
#zip <- readline(prompt="Enter zip code: ")
```

```{r}
data_postcode <- data[data$Postal.Code == "76112" ,]
#Longitude
data_postcode$Longitude <- as.numeric(as.character(data_postcode$Longitude))

#97.211434 -0.01
data_postcode<- data_postcode %>%
  filter(Longitude > -97.2214344 & Longitude < -97.20143 )

#Latitude 
data_postcode$Latitude <- as.numeric(as.character(data_postcode$Latitude))

#32.743529 - 0.01
data_postcode<- data_postcode %>%
  filter(Latitude >32.733529 & Latitude <32.753529)
# sqrFt 1684 - 100
data_postcode <- data_postcode %>%
  filter(Living.Area < 1784 & Living.Area > 1584)

data_postcode$Close.Price <- as.numeric(as.character(data_postcode$Close.Price))
mean(data_postcode$Close.Price)

write.csv(data_postcode, "house.csv")

```