---
title: "Sunique for sell"
author: "Yeyun Xu"
date: "5/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
```
# analyze close status house
```{r}
#read data
data <- read.csv(file = 'combine.csv',na.strings = c("","NA"))
```

#big data cleaning 
```{r}
#data cleaning (omit 90% of the missing data)
data<-data[, which(colMeans(!is.na(data)) > 0.8)]

#get first letter in for subdivision column
subdivision_first_letter <- substr(data$Subdivision.Name,1,6)
#sign into a new columns
data$subdivision_first_letter <- subdivision_first_letter

#year difference
data<-na.omit(data)
data[data$Year.Built <= 1990, "Building_Year"]<- "1990-"
data[data$Year.Built > 1990 & data$Year.Built <= 2011, "Building_Year"] <- "1990-2011"
data[data$Year.Built > 2011 & data$Year.Built <= 2021, "Building_Year"] <- "2011-2021"
data[data$Year.Built == 2022 , "Building_Year"] <- "2022"
```

# filter out good house
```{r}
#check status
table(data$Standard.Status)
#choose CLS status house / sell / SFR
data_SELL <-data[data$Standard.Status =="CLS" & data$Property.Type == "RESI" & data$Property.Sub.Type =="SFR",]

# filter out good area (sold date less than 45 days)
data_SELL <-data_SELL[data_SELL$Days.On.Market<46,]
#set numerical
data_SELL$Close.Price <- as.numeric(data_SELL$Close.Price)

#sort decreasing order
sort(table(data_SELL$Postal.Code), decreasing = TRUE)[1:20]
```

```{r}
#find house less than 5 bed room and 5 bathroom 
data_SELL <-data_SELL[data_SELL$Bedrooms.Total <4 & data_SELL$Bathrooms.Total.Decimal<3.5,]
```

# 1990 house
```{r}
#filter out year 1990
data_SELL_1990 <-data_SELL[data_SELL$Building_Year == "1990-",]
#group by year house price  1990- , 
group_value<- data_SELL_1990 %>%
  group_by(Postal.Code,subdivision_first_letter,Bedrooms.Total,Bathrooms.Total.Decimal) %>%
  summarise(Mean = mean(Close.Price), count_sales = n())

# export to csv
write.csv(group_value, "1990.csv")
```

# 1990-2011
```{r}
#filter out year 1990-2011
data_SELL_1990_2011 <-data_SELL[data_SELL$Building_Year == "1990-2011",]
#group by year house price  1990-2011 , 
group_value <- data_SELL_1990_2011 %>%
  group_by(Postal.Code,subdivision_first_letter,Bedrooms.Total,Bathrooms.Total.Decimal) %>%
  summarise(Mean = mean(Close.Price), count_sales = n())

# export to csv
write.csv(group_value, "1990-2011.csv")
```
#2011-2021
```{r}
#filter out year 1990-2011
data_SELL_2011_2021 <-data_SELL[data_SELL$Building_Year == "2011-2021",]
#group by year house price  1990-2011 , 
data_SELL_2011_2021 %>%
  group_by(Postal.Code,subdivision_first_letter,Bedrooms.Total,Bathrooms.Total.Decimal) %>%
  summarise(Mean = mean(Close.Price), count_sales = n())

# export to csv
write.csv(group_value, "2011-2021.csv")
```
# 2022
```{r}
data_SELL_2022 <-data_SELL[data_SELL$Building_Year == "2022",]
#group by year house price 2022 , 
group_value<-data_SELL_2022 %>%
  group_by(Postal.Code,subdivision_first_letter,Bedrooms.Total,Bathrooms.Total.Decimal) %>%
  summarise(Mean = mean(Close.Price), count_sales = n())

# export to csv
write.csv(group_value, "2022.csv")
```



# Active status house
```{r}
#read data
data_ACT <- read.csv(file = 'Total_Result.csv',na.strings = c("","NA"))
# clean subdivision NA value

```

```{r}

#data_ACT<-data_ACT[, which(colMeans(!is.na(data_ACT)) > 0.6)]
data_ACT <-data_ACT[data_ACT$BedroomsTotal <4 & data_ACT$BathroomsTotalDecimal<3.5,]

#get first letter in for subdivision column
subdivision_first_letter <- substr(data_ACT$SubdivisionName,1,6)
# sign subdivision to it
data_ACT$subdivision_first_letter <- subdivision_first_letter


#choose needed column 
data_ACT <-data_ACT[data_ACT$PropertyType == "Residential" &
                      data_ACT$PropertySubType =="Single Family Residence",]

```
# sign different year
```{r}
# omit na columns
data_ACT <- data_ACT[!is.na(data_ACT$YearBuilt),]

#year difference
data_ACT[data_ACT$YearBuilt <= 1990, "Building_Year"]<- "1990-"
data_ACT[data_ACT$YearBuilt > 1990 & data_ACT$YearBuilt <= 2011, "Building_Year"] <- "1990-2011"
data_ACT[data_ACT$YearBuilt > 2011 & data_ACT$YearBuilt <= 2021, "Building_Year"] <- "2011-2021"
data_ACT[data_ACT$YearBuilt == 2022 , "Building_Year"] <- "2022"
```

# active 房价做对比
```{r}
data_ACT_1990 <-data_ACT[data_ACT$Building_Year == "1990-",]

# 每个subdivision 区 active - close 区 
data_ACT_1990 %>%
  group_by(PostalCode,subdivision_first_letter,BedroomsTotal,BathroomsTotalDecimal) %>%
  summarise(Mean = mean(ListPrice), count = n())

#output 差价
```

```{r}
# 怎么评估卖多少钱
```


```

